<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pde_bsp_plugin"
 *
 * Auto generated by Extension Builder 2014-03-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'PanadeEdu Beispiel Plugin',
	'description' => 'Rendert Beispiel Content ins Frontend.',
	'category' => 'plugin',
	'author' => 'Florian Tatzel',
	'author_email' => 'panadeedu@googlemail.com',
	'author_company' => 'PanadeEdu',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>